### PR TITLE
Added docker debug support for linux

### PR DESCRIPTION
**Pull request by divinebovine**
I've included support for debugging on linux. This should solve [Issue 108](https://github.com/Microsoft/generator-docker/issues/108).

### CODE REVIEW

**Comment by NCarlsonMSFT** [comment]
I was under the impression that the .sh file needed to be updated for linux support. Have you verified that it is working? In particular I think the method openSite wasn't working.

**Comment by divinebovine** [comment]
Yes, I tested on Ubuntu 16.04 using yo aspnet to generate a test site followed by yo docker. I was able to set a breakpoint on the HomeController and after pressing F5, the docker container ran, launched Chrome (going to localhost:5000), and hit my breakpoint.

**Comment by NCarlsonMSFT** [comment]
Have you tested running the task compose in the command pallet, or tested the node scenario? Looking at your launch.json I see that you're using xdg-open command instead of the open command used on osx (which I believe is correct); but without changes, the .sh file is still just using open which I believe won't work.

**Comment by divinebovine** [comment]
No I haven't. I'll take a look at it tonight and revise where necessary.

**Pull request merged**
